import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

const REGISTRY_PATH = path.resolve(
  here,
  "..",
  "..",
  "..",
  "diagnostics",
  "registry.json",
);
const OUTPUT_PATH = path.resolve(
  here,
  "..",
  "src",
  "diagnostics",
  "codes.generated.ts",
);

interface RegistryEntry {
  code: string;
  severity: "error" | "warning";
  rule: string;
  message: string;
  doc: string;
}

interface RegistryFile {
  diagnostics: RegistryEntry[];
}

const rawBytes = await fs.readFile(REGISTRY_PATH);
const hash = crypto.createHash("sha256").update(rawBytes).digest("hex");
const registry = JSON.parse(rawBytes.toString("utf8")) as RegistryFile;

const banner = [
  `// Hash: ${hash}`,
  "// DO NOT EDIT — generated by packages/core/scripts/gen-diagnostic-codes.ts",
  "// Source of truth: caspian/diagnostics/registry.json",
  "// Regenerate with: pnpm gen:codes",
  "// Hash drift is detected by: pnpm verify-codes-hash",
];

const importLine = `import type { DiagnosticDefinition } from "./types.js";`;

const constLines = registry.diagnostics.map((entry) => {
  const constName = entry.code.replace("-", "_");
  return [
    `export const ${constName}: DiagnosticDefinition = {`,
    `  code: ${JSON.stringify(entry.code)},`,
    `  severity: ${JSON.stringify(entry.severity)},`,
    `  rule: ${JSON.stringify(entry.rule)},`,
    `  message: ${JSON.stringify(entry.message)},`,
    `  doc: ${JSON.stringify(entry.doc)},`,
    `};`,
  ].join("\n");
});

const output = [...banner, "", importLine, "", ...constLines, ""].join("\n");

await fs.writeFile(OUTPUT_PATH, output, "utf8");
console.log(
  `[gen-diagnostic-codes] generated ${registry.diagnostics.length} typed constants → ${OUTPUT_PATH}`,
);
