// Hash: b303d1395ec438a29d81b61e5a2a5419ee236b6c38b6feba3021de1df8e803c7
// DO NOT EDIT — generated by packages/core/scripts/gen-diagnostic-codes.ts
// Source of truth: caspian/diagnostics/registry.json
// Regenerate with: pnpm gen:codes
// Hash drift is detected by: pnpm verify-codes-hash

import type { DiagnosticDefinition } from "./types.js";

export const CASPIAN_E001: DiagnosticDefinition = {
  code: "CASPIAN-E001",
  severity: "error",
  rule: "bom-rejection",
  message: "BOM byte sequence (`EF BB BF`) detected at file start",
  doc: "https://caspian.dev/diagnostics#caspian-e001",
};
export const CASPIAN_E002: DiagnosticDefinition = {
  code: "CASPIAN-E002",
  severity: "error",
  rule: "encoding-utf8-required",
  message: "File encoding is not UTF-8",
  doc: "https://caspian.dev/diagnostics#caspian-e002",
};
export const CASPIAN_E003: DiagnosticDefinition = {
  code: "CASPIAN-E003",
  severity: "error",
  rule: "tab-indent-rejection",
  message: "Tab character detected in frontmatter indentation",
  doc: "https://caspian.dev/diagnostics#caspian-e003",
};
export const CASPIAN_E004: DiagnosticDefinition = {
  code: "CASPIAN-E004",
  severity: "error",
  rule: "frontmatter-byte-cap",
  message: "Frontmatter exceeds the 4 KB hard cap",
  doc: "https://caspian.dev/diagnostics#caspian-e004",
};
export const CASPIAN_E005: DiagnosticDefinition = {
  code: "CASPIAN-E005",
  severity: "error",
  rule: "frontmatter-delimiters-required",
  message: "Missing or malformed frontmatter delimiters (`---`)",
  doc: "https://caspian.dev/diagnostics#caspian-e005",
};
export const CASPIAN_E006: DiagnosticDefinition = {
  code: "CASPIAN-E006",
  severity: "error",
  rule: "yaml-parse-error",
  message: "YAML parse error in frontmatter",
  doc: "https://caspian.dev/diagnostics#caspian-e006",
};
export const CASPIAN_E007: DiagnosticDefinition = {
  code: "CASPIAN-E007",
  severity: "error",
  rule: "yaml-1-1-boolean-coercion",
  message: "Unquoted YAML 1.1 boolean-like value (`on`/`off`/`yes`/`no`/`y`/`n`)",
  doc: "https://caspian.dev/diagnostics#caspian-e007",
};
export const CASPIAN_E008: DiagnosticDefinition = {
  code: "CASPIAN-E008",
  severity: "error",
  rule: "type-required",
  message: "Field `type` is missing or empty",
  doc: "https://caspian.dev/diagnostics#caspian-e008",
};
export const CASPIAN_E009: DiagnosticDefinition = {
  code: "CASPIAN-E009",
  severity: "error",
  rule: "type-namespace-name-form",
  message: "Field `type` is not in `<namespace>:<name>` form",
  doc: "https://caspian.dev/diagnostics#caspian-e009",
};
export const CASPIAN_E010: DiagnosticDefinition = {
  code: "CASPIAN-E010",
  severity: "error",
  rule: "requires-must-be-array",
  message: "Field `requires` is not an array",
  doc: "https://caspian.dev/diagnostics#caspian-e010",
};
export const CASPIAN_E011: DiagnosticDefinition = {
  code: "CASPIAN-E011",
  severity: "error",
  rule: "requires-entry-type-required",
  message: "Entry in `requires` is missing `type`",
  doc: "https://caspian.dev/diagnostics#caspian-e011",
};
export const CASPIAN_E012: DiagnosticDefinition = {
  code: "CASPIAN-E012",
  severity: "error",
  rule: "requires-entry-invalid-shape",
  message: "Entry in `requires` has an invalid shape",
  doc: "https://caspian.dev/diagnostics#caspian-e012",
};
export const CASPIAN_E013: DiagnosticDefinition = {
  code: "CASPIAN-E013",
  severity: "error",
  rule: "produces-must-be-object",
  message: "Field `produces` is not an object",
  doc: "https://caspian.dev/diagnostics#caspian-e013",
};
export const CASPIAN_E014: DiagnosticDefinition = {
  code: "CASPIAN-E014",
  severity: "error",
  rule: "produces-type-required",
  message: "Field `produces` is missing `type`",
  doc: "https://caspian.dev/diagnostics#caspian-e014",
};
export const CASPIAN_W001: DiagnosticDefinition = {
  code: "CASPIAN-W001",
  severity: "warning",
  rule: "frontmatter-field-allow-list",
  message: "Unrecognized frontmatter field outside the recognized allow-list",
  doc: "https://caspian.dev/diagnostics#caspian-w001",
};
export const CASPIAN_W002: DiagnosticDefinition = {
  code: "CASPIAN-W002",
  severity: "warning",
  rule: "type-canonical-namespace",
  message: "Field `type` uses a namespace outside the canonical `core:*` registry",
  doc: "https://caspian.dev/diagnostics#caspian-w002",
};
export const CASPIAN_W003: DiagnosticDefinition = {
  code: "CASPIAN-W003",
  severity: "warning",
  rule: "schema-version-recognized",
  message: "Field `schema_version` value is not recognized by this validator",
  doc: "https://caspian.dev/diagnostics#caspian-w003",
};
export const CASPIAN_W004: DiagnosticDefinition = {
  code: "CASPIAN-W004",
  severity: "warning",
  rule: "core-namespace-name-not-in-vocabulary",
  message: "Field `type` uses a `core:` name outside the canonical vocabulary",
  doc: "https://caspian.dev/diagnostics#caspian-w004",
};
