import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgPath = path.resolve(here, "..", "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as { version: string };

const out = `// DO NOT EDIT — generated by packages/cli/scripts/gen-version.ts
// Source of truth: packages/cli/package.json
// Regenerate with: pnpm -F @caspian-dev/cli gen:version

export const VERSION = ${JSON.stringify(pkg.version)};
`;

const target = path.resolve(here, "..", "src", "version.generated.ts");
writeFileSync(target, out, "utf-8");
console.log(
  `Wrote ${path.relative(process.cwd(), target)} (VERSION = "${pkg.version}")`,
);
