// DO NOT EDIT — generated by packages/cli/scripts/gen-version.ts
// Source of truth: packages/cli/package.json
// Regenerate with: pnpm -F @caspian-dev/cli gen:version

export const VERSION = "0.0.1";
